/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import UML.Jornada;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jems.JEMS;

/**
 *
 * @author Miguel Barros
 * @author Eric Muñoz
 *
 * @version %I%, %G%
 * @since 1.0
 */
public class V_Admin extends javax.swing.JFrame {

    /**
     * Creates new form V_Inicio
     */
    public V_Admin() {
        setUndecorated(true);
        initComponents();
        myInitComponents();
    }

    public void myInitComponents() {
        setSize(1280, 720);
        setLocationRelativeTo(null);
        bVolver.setVisible(false);
    }

    private static String operacion;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        lbEquipo1 = new javax.swing.JLabel();
        lbEquipo2 = new javax.swing.JLabel();
        lbEquipo3 = new javax.swing.JLabel();
        lbEquipo4 = new javax.swing.JLabel();
        lbEquipo5 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        bCrearLiga = new javax.swing.JButton();
        bEquipo = new javax.swing.JButton();
        bJugador = new javax.swing.JButton();
        bDueño = new javax.swing.JButton();
        bUsuario = new javax.swing.JButton();
        bAlta = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bBaja = new javax.swing.JButton();
        bConsultarUno = new javax.swing.JButton();
        bConsultarMuchos = new javax.swing.JButton();
        lbEquipo = new javax.swing.JLabel();
        lbJugador = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbDueño = new javax.swing.JLabel();
        lbTituloAdmin = new javax.swing.JLabel();
        lbRiot = new javax.swing.JLabel();
        lbVersion = new javax.swing.JLabel();
        bVolver = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        lbBackgroundUsuario = new javax.swing.JLabel();
        lbFiller = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        miModificarJugador = new javax.swing.JMenuItem();
        miAltaJugador = new javax.swing.JMenuItem();
        miBajaJugador = new javax.swing.JMenuItem();
        miConsultarJugador = new javax.swing.JMenuItem();
        miConsultarJugadores = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        miModificarEquipo = new javax.swing.JMenuItem();
        miAltaEquipo = new javax.swing.JMenuItem();
        miBajaEquipo = new javax.swing.JMenuItem();
        miConsultarEquipo = new javax.swing.JMenuItem();
        miConsultarEquipos = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        miModificarDueño = new javax.swing.JMenuItem();
        miAltaDueño = new javax.swing.JMenuItem();
        miBajaDueño = new javax.swing.JMenuItem();
        miConsultarDueño = new javax.swing.JMenuItem();
        miConsultarDueños = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        miModificarUsuario = new javax.swing.JMenuItem();
        miAltaUsuario = new javax.swing.JMenuItem();
        miBajaUsuario = new javax.swing.JMenuItem();
        miConsultarUsuario = new javax.swing.JMenuItem();
        miConsultarUsuarios = new javax.swing.JMenuItem();
        mIntroducirResultado = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        miJornada1 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        miJornada2 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        miJornada3 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        miJornada4 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        miJornada5 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        miJornada6 = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        miJornada7 = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        miJornada8 = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        miJornada9 = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        miJornada10 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        miVisualizarLiga = new javax.swing.JMenuItem();
        miVisualizarClasificacion = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();

        jMenuItem15.setText("jMenuItem15");

        jMenuItem16.setText("jMenuItem16");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbEquipo1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        lbEquipo1.setForeground(new java.awt.Color(0, 0, 0));
        lbEquipo1.setText("BORRAR");
        getContentPane().add(lbEquipo1);
        lbEquipo1.setBounds(190, 310, 102, 40);

        lbEquipo2.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        lbEquipo2.setForeground(new java.awt.Color(0, 0, 0));
        lbEquipo2.setText("AÑADIR");
        getContentPane().add(lbEquipo2);
        lbEquipo2.setBounds(190, 150, 100, 40);

        lbEquipo3.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        lbEquipo3.setForeground(new java.awt.Color(0, 0, 0));
        lbEquipo3.setText("CONSULTAR UNO");
        getContentPane().add(lbEquipo3);
        lbEquipo3.setBounds(190, 390, 210, 40);

        lbEquipo4.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        lbEquipo4.setForeground(new java.awt.Color(0, 0, 0));
        lbEquipo4.setText("CONSULTAR TODOS");
        getContentPane().add(lbEquipo4);
        lbEquipo4.setBounds(190, 470, 240, 40);

        lbEquipo5.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        lbEquipo5.setForeground(new java.awt.Color(0, 0, 0));
        lbEquipo5.setText("EDITAR");
        getContentPane().add(lbEquipo5);
        lbEquipo5.setBounds(190, 230, 90, 40);

        jToggleButton1.setText("jToggleButton1");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(0, 0, 0, 0);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 0, 0);

        bCrearLiga.setBackground(new java.awt.Color(252, 124, 0));
        bCrearLiga.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        bCrearLiga.setForeground(new java.awt.Color(255, 255, 255));
        bCrearLiga.setText("CREAR LIGA");
        bCrearLiga.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bCrearLiga.setBorderPainted(false);
        bCrearLiga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCrearLiga.setFocusPainted(false);
        bCrearLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearLigaActionPerformed(evt);
            }
        });
        getContentPane().add(bCrearLiga);
        bCrearLiga.setBounds(740, 30, 410, 80);

        bEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/equipo.png"))); // NOI18N
        bEquipo.setBorder(null);
        bEquipo.setBorderPainted(false);
        bEquipo.setContentAreaFilled(false);
        bEquipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEquipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(bEquipo);
        bEquipo.setBounds(90, 240, 270, 80);

        bJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/jugador.png"))); // NOI18N
        bJugador.setBorder(null);
        bJugador.setBorderPainted(false);
        bJugador.setContentAreaFilled(false);
        bJugador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bJugador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(bJugador);
        bJugador.setBounds(90, 440, 270, 80);

        bDueño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/dueño.png"))); // NOI18N
        bDueño.setBorder(null);
        bDueño.setBorderPainted(false);
        bDueño.setContentAreaFilled(false);
        bDueño.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bDueño.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDueñoActionPerformed(evt);
            }
        });
        getContentPane().add(bDueño);
        bDueño.setBounds(90, 340, 270, 80);

        bUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/usuario.png"))); // NOI18N
        bUsuario.setBorder(null);
        bUsuario.setBorderPainted(false);
        bUsuario.setContentAreaFilled(false);
        bUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(bUsuario);
        bUsuario.setBounds(90, 140, 270, 80);

        bAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/añadir.png"))); // NOI18N
        bAlta.setBorder(null);
        bAlta.setBorderPainted(false);
        bAlta.setContentAreaFilled(false);
        bAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAlta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAltaActionPerformed(evt);
            }
        });
        getContentPane().add(bAlta);
        bAlta.setBounds(80, 130, 320, 80);

        bModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/editar.png"))); // NOI18N
        bModificar.setBorder(null);
        bModificar.setBorderPainted(false);
        bModificar.setContentAreaFilled(false);
        bModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bModificar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });
        getContentPane().add(bModificar);
        bModificar.setBounds(80, 220, 320, 70);

        bBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/borrar.png"))); // NOI18N
        bBaja.setBorder(null);
        bBaja.setBorderPainted(false);
        bBaja.setContentAreaFilled(false);
        bBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBaja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBajaActionPerformed(evt);
            }
        });
        getContentPane().add(bBaja);
        bBaja.setBounds(80, 300, 320, 70);

        bConsultarUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/buscar_uno.png"))); // NOI18N
        bConsultarUno.setBorder(null);
        bConsultarUno.setBorderPainted(false);
        bConsultarUno.setContentAreaFilled(false);
        bConsultarUno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bConsultarUno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bConsultarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarUnoActionPerformed(evt);
            }
        });
        getContentPane().add(bConsultarUno);
        bConsultarUno.setBounds(80, 380, 320, 70);

        bConsultarMuchos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/buscar_varios.png"))); // NOI18N
        bConsultarMuchos.setBorder(null);
        bConsultarMuchos.setBorderPainted(false);
        bConsultarMuchos.setContentAreaFilled(false);
        bConsultarMuchos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bConsultarMuchos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bConsultarMuchos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarMuchosActionPerformed(evt);
            }
        });
        getContentPane().add(bConsultarMuchos);
        bConsultarMuchos.setBounds(80, 460, 320, 70);

        lbEquipo.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        lbEquipo.setForeground(new java.awt.Color(0, 0, 0));
        lbEquipo.setText("EQUIPO");
        getContentPane().add(lbEquipo);
        lbEquipo.setBounds(200, 260, 90, 40);

        lbJugador.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        lbJugador.setForeground(new java.awt.Color(0, 0, 0));
        lbJugador.setText("JUGADOR");
        getContentPane().add(lbJugador);
        lbJugador.setBounds(200, 460, 120, 40);

        lbUsuario.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lbUsuario.setText("USUARIO");
        getContentPane().add(lbUsuario);
        lbUsuario.setBounds(200, 160, 110, 40);

        lbDueño.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        lbDueño.setForeground(new java.awt.Color(0, 0, 0));
        lbDueño.setText("DUEÑO");
        getContentPane().add(lbDueño);
        lbDueño.setBounds(200, 360, 90, 40);

        lbTituloAdmin.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        lbTituloAdmin.setForeground(new java.awt.Color(0, 0, 0));
        lbTituloAdmin.setText("<HTML>ADMINISTRAR <BR> BASE DE DATOS</HTML> ");
        getContentPane().add(lbTituloAdmin);
        lbTituloAdmin.setBounds(80, 10, 300, 100);

        lbRiot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/riotLogo.png"))); // NOI18N
        getContentPane().add(lbRiot);
        lbRiot.setBounds(10, 610, 100, 60);

        lbVersion.setFont(new java.awt.Font("Source Serif Pro Black", 3, 12)); // NOI18N
        lbVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVersion.setText("FINAL_BUILD_V1.0.0");
        getContentPane().add(lbVersion);
        lbVersion.setBounds(1100, 620, 180, 40);

        bVolver.setBackground(new java.awt.Color(13, 9, 32));
        bVolver.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        bVolver.setForeground(new java.awt.Color(255, 255, 255));
        bVolver.setText("VOLVER");
        bVolver.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bVolver.setBorderPainted(false);
        bVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVolver.setFocusPainted(false);
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });
        getContentPane().add(bVolver);
        bVolver.setBounds(150, 560, 170, 30);

        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/error.png"))); // NOI18N
        bSalir.setBorderPainted(false);
        bSalir.setContentAreaFilled(false);
        bSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSalir.setFocusPainted(false);
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        getContentPane().add(bSalir);
        bSalir.setBounds(1230, 10, 40, 40);

        lbBackgroundUsuario.setBackground(new java.awt.Color(13, 9, 32));
        lbBackgroundUsuario.setForeground(new java.awt.Color(13, 9, 32));
        lbBackgroundUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/background_secondary_color.png"))); // NOI18N
        getContentPane().add(lbBackgroundUsuario);
        lbBackgroundUsuario.setBounds(0, 0, 440, 720);

        lbFiller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Nunu.jpg"))); // NOI18N
        getContentPane().add(lbFiller);
        lbFiller.setBounds(0, 0, 1280, 720);

        jMenu1.setBorder(null);
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/sql developer_opt.png"))); // NOI18N
        jMenu1.setText("BBDD");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jMenu3.setText("Jugador");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        miModificarJugador.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        miModificarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/modificar_opt.png"))); // NOI18N
        miModificarJugador.setText("Modificar");
        miModificarJugador.setIconTextGap(1);
        miModificarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModificarJugadorActionPerformed(evt);
            }
        });
        jMenu3.add(miModificarJugador);

        miAltaJugador.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        miAltaJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/alta_opt.jpg"))); // NOI18N
        miAltaJugador.setText("Alta");
        miAltaJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAltaJugadorActionPerformed(evt);
            }
        });
        jMenu3.add(miAltaJugador);

        miBajaJugador.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        miBajaJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/borrar_opt.png"))); // NOI18N
        miBajaJugador.setText("Baja");
        miBajaJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBajaJugadorActionPerformed(evt);
            }
        });
        jMenu3.add(miBajaJugador);

        miConsultarJugador.setText("ConsultarJugador");
        miConsultarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarJugadorActionPerformed(evt);
            }
        });
        jMenu3.add(miConsultarJugador);

        miConsultarJugadores.setText("ConsultarJugadores");
        miConsultarJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarJugadoresActionPerformed(evt);
            }
        });
        jMenu3.add(miConsultarJugadores);

        jMenu1.add(jMenu3);
        jMenu1.add(jSeparator2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/equipo_opt.jpg"))); // NOI18N
        jMenu4.setText("Equipo");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        miModificarEquipo.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        miModificarEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/modificar_opt.png"))); // NOI18N
        miModificarEquipo.setText("Modificar");
        miModificarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModificarEquipoActionPerformed(evt);
            }
        });
        jMenu4.add(miModificarEquipo);

        miAltaEquipo.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        miAltaEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/alta_opt.jpg"))); // NOI18N
        miAltaEquipo.setText("Alta");
        miAltaEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAltaEquipoActionPerformed(evt);
            }
        });
        jMenu4.add(miAltaEquipo);

        miBajaEquipo.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        miBajaEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/borrar_opt.png"))); // NOI18N
        miBajaEquipo.setText("Baja");
        miBajaEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBajaEquipoActionPerformed(evt);
            }
        });
        jMenu4.add(miBajaEquipo);

        miConsultarEquipo.setText("ConsultarEquipo");
        miConsultarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarEquipoActionPerformed(evt);
            }
        });
        jMenu4.add(miConsultarEquipo);

        miConsultarEquipos.setText("ConsultarEquipos");
        miConsultarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarEquiposActionPerformed(evt);
            }
        });
        jMenu4.add(miConsultarEquipos);

        jMenu1.add(jMenu4);
        jMenu1.add(jSeparator3);

        jMenu5.setText("Dueño");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        miModificarDueño.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        miModificarDueño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/modificar_opt.png"))); // NOI18N
        miModificarDueño.setText("Modificar");
        miModificarDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModificarDueñoActionPerformed(evt);
            }
        });
        jMenu5.add(miModificarDueño);

        miAltaDueño.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        miAltaDueño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/alta_opt.jpg"))); // NOI18N
        miAltaDueño.setText("Alta");
        miAltaDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAltaDueñoActionPerformed(evt);
            }
        });
        jMenu5.add(miAltaDueño);

        miBajaDueño.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        miBajaDueño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/borrar_opt.png"))); // NOI18N
        miBajaDueño.setText("Baja");
        miBajaDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBajaDueñoActionPerformed(evt);
            }
        });
        jMenu5.add(miBajaDueño);

        miConsultarDueño.setText("ConsultarDueño");
        miConsultarDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarDueñoActionPerformed(evt);
            }
        });
        jMenu5.add(miConsultarDueño);

        miConsultarDueños.setText("ConsultarDueños");
        miConsultarDueños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarDueñosActionPerformed(evt);
            }
        });
        jMenu5.add(miConsultarDueños);

        jMenu1.add(jMenu5);
        jMenu1.add(jSeparator4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Usuario_opt.png"))); // NOI18N
        jMenu6.setText("Usuario");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        miModificarUsuario.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        miModificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/modificar_opt.png"))); // NOI18N
        miModificarUsuario.setText("Modificar");
        miModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModificarUsuarioActionPerformed(evt);
            }
        });
        jMenu6.add(miModificarUsuario);

        miAltaUsuario.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        miAltaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/alta_opt.jpg"))); // NOI18N
        miAltaUsuario.setText("Alta");
        miAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAltaUsuarioActionPerformed(evt);
            }
        });
        jMenu6.add(miAltaUsuario);

        miBajaUsuario.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        miBajaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/borrar_opt.png"))); // NOI18N
        miBajaUsuario.setText("Baja");
        miBajaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBajaUsuarioActionPerformed(evt);
            }
        });
        jMenu6.add(miBajaUsuario);

        miConsultarUsuario.setText("ConsultarUsuario");
        miConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarUsuarioActionPerformed(evt);
            }
        });
        jMenu6.add(miConsultarUsuario);

        miConsultarUsuarios.setText("ConsultarUsuarios");
        miConsultarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarUsuariosActionPerformed(evt);
            }
        });
        jMenu6.add(miConsultarUsuarios);

        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        mIntroducirResultado.setText("Introducir Resultado");
        mIntroducirResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mIntroducirResultado.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        mIntroducirResultado.setIconTextGap(10);
        mIntroducirResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIntroducirResultadoActionPerformed(evt);
            }
        });
        mIntroducirResultado.add(jSeparator1);
        mIntroducirResultado.add(jSeparator5);

        miJornada1.setText("Jornada 1");
        miJornada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJornada1ActionPerformed(evt);
            }
        });
        mIntroducirResultado.add(miJornada1);
        mIntroducirResultado.add(jSeparator7);

        miJornada2.setText("Jornada 2");
        miJornada2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJornada2ActionPerformed(evt);
            }
        });
        mIntroducirResultado.add(miJornada2);
        mIntroducirResultado.add(jSeparator8);

        miJornada3.setText("Jornada 3");
        miJornada3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJornada3ActionPerformed(evt);
            }
        });
        mIntroducirResultado.add(miJornada3);
        mIntroducirResultado.add(jSeparator9);

        miJornada4.setText("Jornada 4");
        miJornada4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJornada4ActionPerformed(evt);
            }
        });
        mIntroducirResultado.add(miJornada4);
        mIntroducirResultado.add(jSeparator10);

        miJornada5.setText("Jornada 5");
        miJornada5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJornada5ActionPerformed(evt);
            }
        });
        mIntroducirResultado.add(miJornada5);
        mIntroducirResultado.add(jSeparator11);

        miJornada6.setText("Jornada 6");
        miJornada6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJornada6ActionPerformed(evt);
            }
        });
        mIntroducirResultado.add(miJornada6);
        mIntroducirResultado.add(jSeparator12);

        miJornada7.setText("Jornada 7");
        miJornada7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJornada7ActionPerformed(evt);
            }
        });
        mIntroducirResultado.add(miJornada7);
        mIntroducirResultado.add(jSeparator13);

        miJornada8.setText("Jornada 8");
        miJornada8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJornada8ActionPerformed(evt);
            }
        });
        mIntroducirResultado.add(miJornada8);
        mIntroducirResultado.add(jSeparator14);

        miJornada9.setText("Jornada 9");
        miJornada9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJornada9ActionPerformed(evt);
            }
        });
        mIntroducirResultado.add(miJornada9);
        mIntroducirResultado.add(jSeparator15);

        miJornada10.setText("Jornada 10");
        miJornada10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJornada10ActionPerformed(evt);
            }
        });
        mIntroducirResultado.add(miJornada10);

        jMenuBar1.add(mIntroducirResultado);

        jMenu7.setBorder(null);
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ojos_opt.png"))); // NOI18N
        jMenu7.setText("Visualizar");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jMenu7.setIconTextGap(7);

        miVisualizarLiga.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        miVisualizarLiga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/SLO_opt.png"))); // NOI18N
        miVisualizarLiga.setText("Liga");
        miVisualizarLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarLigaActionPerformed(evt);
            }
        });
        jMenu7.add(miVisualizarLiga);

        miVisualizarClasificacion.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        miVisualizarClasificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clasificacion_opt.jpg"))); // NOI18N
        miVisualizarClasificacion.setText("Clasificacion");
        miVisualizarClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarClasificacionActionPerformed(evt);
            }
        });
        jMenu7.add(miVisualizarClasificacion);
        jMenu7.add(jSeparator6);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Funcion que nos dirije a la clase mostrarVentanaJugador pasandole el
     * parametro operacion para saber el tipo de operacion a realizar
     *
     * @param evt pulsar el boton
     */
    private void miModificarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModificarJugadorActionPerformed
        try {
            operacion = "modificar";
            ControladorVistas.mostrarVentanaJugador(operacion);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miModificarJugadorActionPerformed
    /**
     * Funcion que nos dirije a la clase mostrarVentanaJugador pasandole el
     * parametro operacion para saber el tipo de operacion a realizar
     *
     * @param evt pulsar el boton
     */
    private void miBajaJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBajaJugadorActionPerformed
        try {
            operacion = "baja";
            ControladorVistas.mostrarVentanaJugador(operacion);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miBajaJugadorActionPerformed
    /**
     * Funcion que nos dirije a la clase mostrarVentanaAdminUsuario pasandole el
     * parametro operacion para saber el tipo de operacion a realizar
     *
     * @param evt pulsar el boton
     */
    private void miBajaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBajaUsuarioActionPerformed
        operacion = "baja";
        ControladorVistas.mostrarVentanaAdminUsuario(operacion);
    }//GEN-LAST:event_miBajaUsuarioActionPerformed
    /**
     * Funcion que nos dirije a la clase mostrarVentanaJugador pasandole el
     * parametro operacion para saber el tipo de operacion a realizar
     *
     * @param evt pulsar el boton
     */
    private void miAltaJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAltaJugadorActionPerformed
        try {
            operacion = "alta";
            ControladorVistas.mostrarVentanaJugador(operacion);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miAltaJugadorActionPerformed
    /**
     * Funcion que nos dirije a la clase mostrarVentanaEquipo pasandole el
     * parametro operacion para saber el tipo de operacion a realizar
     *
     * @param evt pulsar el boton
     */
    private void miModificarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModificarEquipoActionPerformed
        try {
            operacion = "modificar";

            ControladorVistas.mostrarVentanaEquipo(operacion);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miModificarEquipoActionPerformed
    /**
     * Funcion que nos dirije a la clase mostrarVentanaEquipo pasandole el
     * parametro operacion para saber el tipo de operacion a realizar
     *
     * @param evt pulsar el boton
     */
    private void miAltaEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAltaEquipoActionPerformed
        try {
            operacion = "alta";
            ControladorVistas.mostrarVentanaEquipo(operacion);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miAltaEquipoActionPerformed
    /**
     * Funcion que nos dirije a la clase mostrarVentanaEquipo pasandole el
     * parametro operacion para saber el tipo de operacion a realizar
     *
     * @param evt pulsar el boton
     */
    private void miBajaEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBajaEquipoActionPerformed
        try {
            operacion = "baja";
            ControladorVistas.mostrarVentanaEquipo(operacion);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miBajaEquipoActionPerformed

    private void miModificarDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModificarDueñoActionPerformed
        operacion = "modificar";
        ControladorVistas.mostrarVentanaDueño(operacion);
    }//GEN-LAST:event_miModificarDueñoActionPerformed
    /**
     * Funcion que nos dirije a la clase mostrarVentanaDueño pasandole el
     * parametro operacion para saber el tipo de operacion a realizar
     *
     * @param evt pulsar el boton
     */
    private void miAltaDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAltaDueñoActionPerformed
        operacion = "alta";
        ControladorVistas.mostrarVentanaDueño(operacion);
    }//GEN-LAST:event_miAltaDueñoActionPerformed
    /**
     * Funcion que nos dirije a la clase mostrarVentanaDueño pasandole el
     * parametro operacion para saber el tipo de operacion a realizar
     *
     * @param evt pulsar el boton
     */
    private void miBajaDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBajaDueñoActionPerformed
        operacion = "baja";
        ControladorVistas.mostrarVentanaDueño(operacion);
    }//GEN-LAST:event_miBajaDueñoActionPerformed

    private void miModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModificarUsuarioActionPerformed
        operacion = "modificar";
        ControladorVistas.mostrarVentanaAdminUsuario(operacion);
    }//GEN-LAST:event_miModificarUsuarioActionPerformed

    private void miAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAltaUsuarioActionPerformed
        operacion = "alta";
        ControladorVistas.mostrarVentanaAdminUsuario(operacion);
    }//GEN-LAST:event_miAltaUsuarioActionPerformed

    private void bCrearLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearLigaActionPerformed
        ControladorVistas.mostrarVentanaCreacion();
    }//GEN-LAST:event_bCrearLigaActionPerformed
    /**
     * Funcion que nos dirije a la clase mostrarVentanaJugador pasandole el
     * parametro operacion para saber el tipo de operacion a realizar
     *
     * @param evt pulsar el boton
     */
    private void miConsultarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarJugadorActionPerformed
        try {
            operacion = "consulta";
            ControladorVistas.mostrarVentanaJugador(operacion);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miConsultarJugadorActionPerformed
    /**
     * Funcion que nos dirije a la clase mostrarVentanaLista pasandole
     * listajugadores
     *
     * @param evt pulsar el boton
     */
    private void miConsultarJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarJugadoresActionPerformed
        try {
            String listaJugadores = JEMS.crearListaJugadores();
            ControladorVistas.mostrarVentanaLista(listaJugadores);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miConsultarJugadoresActionPerformed

    private void miConsultarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarEquipoActionPerformed
        try {
            operacion = "consulta";
            ControladorVistas.mostrarVentanaEquipo(operacion);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miConsultarEquipoActionPerformed

    /**
     * Funcion que nos dirije a la clase mostrarVentanaLista pasandole
     * listaEquipos
     *
     * @param evt pulsar el boton
     */

    private void miConsultarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarEquiposActionPerformed
        try {
            String listaEquipos = JEMS.crearListaEquipos();
            ControladorVistas.mostrarVentanaLista(listaEquipos);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miConsultarEquiposActionPerformed
    /**
     * Funcion que nos dirije a la clase mostrarVentanaDueño pasandole el
     * parametro operacion para saber el tipo de operacion a realizar
     *
     * @param evt pulsar el boton
     */
    private void miConsultarDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarDueñoActionPerformed
        operacion = "consulta";
        ControladorVistas.mostrarVentanaDueño(operacion);
    }//GEN-LAST:event_miConsultarDueñoActionPerformed
    /**
     * Funcion que nos dirije a la clase mostrarVentanaLista pasandole
     * listaDueños
     *
     * @param evt pulsar el boton
     */
    private void miConsultarDueñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarDueñosActionPerformed
        try {
            String listaDueños = JEMS.crearListaDueños();
            ControladorVistas.mostrarVentanaLista(listaDueños);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miConsultarDueñosActionPerformed
    /**
     * Funcion que nos dirije a la clase mostrarVentanaAdminUsuario pasandole el
     * parametro operacion para saber el tipo de operacion a realizar
     *
     * @param evt pulsar el boton
     */
    private void miConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarUsuarioActionPerformed
        operacion = "consulta";
        ControladorVistas.mostrarVentanaAdminUsuario(operacion);
    }//GEN-LAST:event_miConsultarUsuarioActionPerformed
    /**
     * Funcion que nos dirije a la clase mostrarVentanaLista pasandole
     * listaUsuarios
     *
     * @param evt pulsar el boton
     */
    private void miConsultarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarUsuariosActionPerformed
        try {
            String listaUsuarios = JEMS.crearListaUsuarios();
            ControladorVistas.mostrarVentanaLista(listaUsuarios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_miConsultarUsuariosActionPerformed

    private void miVisualizarLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarLigaActionPerformed
        try {
            ControladorVistas.mostrarVentanaJornadas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miVisualizarLigaActionPerformed

    private void miVisualizarClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarClasificacionActionPerformed
        try {
            ControladorVistas.mostrarVentanaLiga();
        } catch (Exception ex) {
            Logger.getLogger(V_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miVisualizarClasificacionActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void mIntroducirResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIntroducirResultadoActionPerformed

    }//GEN-LAST:event_mIntroducirResultadoActionPerformed

    private void miJornada10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJornada10ActionPerformed
        try {
            ArrayList<Jornada> jornadas = new ArrayList<Jornada>();
            jornadas = JEMS.buscarJornadas();
            int numJornada = 10;
            ControladorVistas.mostrarVentanaResultado(jornadas, numJornada);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miJornada10ActionPerformed

    private void miJornada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJornada1ActionPerformed
        try {
            ArrayList<Jornada> jornadas = new ArrayList<Jornada>();
            jornadas = JEMS.buscarJornadas();
            int numJornada = 1;
            ControladorVistas.mostrarVentanaResultado(jornadas, numJornada);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miJornada1ActionPerformed

    private void miJornada2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJornada2ActionPerformed
        try {
            ArrayList<Jornada> jornadas = new ArrayList<Jornada>();
            jornadas = JEMS.buscarJornadas();
            int numJornada = 2;
            ControladorVistas.mostrarVentanaResultado(jornadas, numJornada);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miJornada2ActionPerformed

    private void miJornada3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJornada3ActionPerformed
        try {
            ArrayList<Jornada> jornadas = new ArrayList<Jornada>();
            jornadas = JEMS.buscarJornadas();
            int numJornada = 3;
            ControladorVistas.mostrarVentanaResultado(jornadas, numJornada);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miJornada3ActionPerformed

    private void miJornada4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJornada4ActionPerformed
        try {
            ArrayList<Jornada> jornadas = new ArrayList<Jornada>();
            jornadas = JEMS.buscarJornadas();
            int numJornada = 4;
            ControladorVistas.mostrarVentanaResultado(jornadas, numJornada);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miJornada4ActionPerformed

    private void miJornada5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJornada5ActionPerformed
        try {
            ArrayList<Jornada> jornadas = new ArrayList<Jornada>();
            jornadas = JEMS.buscarJornadas();
            int numJornada = 5;
            ControladorVistas.mostrarVentanaResultado(jornadas, numJornada);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miJornada5ActionPerformed

    private void miJornada6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJornada6ActionPerformed
        try {
            ArrayList<Jornada> jornadas = new ArrayList<Jornada>();
            jornadas = JEMS.buscarJornadas();
            int numJornada = 6;
            ControladorVistas.mostrarVentanaResultado(jornadas, numJornada);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miJornada6ActionPerformed

    private void miJornada7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJornada7ActionPerformed
        try {
            ArrayList<Jornada> jornadas = new ArrayList<Jornada>();
            jornadas = JEMS.buscarJornadas();
            int numJornada = 7;
            ControladorVistas.mostrarVentanaResultado(jornadas, numJornada);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miJornada7ActionPerformed

    private void miJornada8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJornada8ActionPerformed
        try {
            ArrayList<Jornada> jornadas = new ArrayList<Jornada>();
            jornadas = JEMS.buscarJornadas();
            int numJornada = 8;
            ControladorVistas.mostrarVentanaResultado(jornadas, numJornada);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miJornada8ActionPerformed

    private void miJornada9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJornada9ActionPerformed
        try {
            ArrayList<Jornada> jornadas = new ArrayList<Jornada>();
            jornadas = JEMS.buscarJornadas();
            int numJornada = 9;
            ControladorVistas.mostrarVentanaResultado(jornadas, numJornada);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_miJornada9ActionPerformed

    private void bUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUsuarioActionPerformed
        bVolver.setVisible(true);
        lbTituloAdmin.setText("USUARIO");
    }//GEN-LAST:event_bUsuarioActionPerformed

    private void bEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEquipoActionPerformed
        bVolver.setVisible(true);
        lbTituloAdmin.setText("EQUIPO");
    }//GEN-LAST:event_bEquipoActionPerformed

    private void bDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDueñoActionPerformed
        bVolver.setVisible(true);
        lbTituloAdmin.setText("DUEÑO");
    }//GEN-LAST:event_bDueñoActionPerformed

    private void bJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJugadorActionPerformed
        bVolver.setVisible(true);
        lbTituloAdmin.setText("JUGADOR");
    }//GEN-LAST:event_bJugadorActionPerformed

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        bVolver.setVisible(false);
        lbTituloAdmin.setText("<HTML>ADMINISTRAR <BR> BASE DE DATOS</HTML>");
    }//GEN-LAST:event_bVolverActionPerformed

    private void bAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAltaActionPerformed
        if (lbTituloAdmin.getText().equalsIgnoreCase("USUARIO")) {
            operacion = "alta";
            ControladorVistas.mostrarVentanaAdminUsuario(operacion);
        } else if (lbTituloAdmin.getText().equalsIgnoreCase("JUGADOR")) {
            try {
                operacion = "alta";
                ControladorVistas.mostrarVentanaJugador(operacion);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
            }
        } else if (lbTituloAdmin.getText().equalsIgnoreCase("EQUIPO")) {
            try {
                operacion = "alta";
                ControladorVistas.mostrarVentanaEquipo(operacion);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
            }
        } else if (lbTituloAdmin.getText().equalsIgnoreCase("DUEÑO")) {
            operacion = "alta";
            ControladorVistas.mostrarVentanaDueño(operacion);
        }

    }//GEN-LAST:event_bAltaActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed

    }//GEN-LAST:event_bModificarActionPerformed

    private void bBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBajaActionPerformed

    }//GEN-LAST:event_bBajaActionPerformed

    private void bConsultarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarUnoActionPerformed

    }//GEN-LAST:event_bConsultarUnoActionPerformed

    private void bConsultarMuchosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarMuchosActionPerformed

    }//GEN-LAST:event_bConsultarMuchosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlta;
    private javax.swing.JButton bBaja;
    private javax.swing.JButton bConsultarMuchos;
    private javax.swing.JButton bConsultarUno;
    private javax.swing.JButton bCrearLiga;
    private javax.swing.JButton bDueño;
    private javax.swing.JButton bEquipo;
    private javax.swing.JButton bJugador;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton bUsuario;
    private javax.swing.JButton bVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbBackgroundUsuario;
    private javax.swing.JLabel lbDueño;
    private javax.swing.JLabel lbEquipo;
    private javax.swing.JLabel lbEquipo1;
    private javax.swing.JLabel lbEquipo2;
    private javax.swing.JLabel lbEquipo3;
    private javax.swing.JLabel lbEquipo4;
    private javax.swing.JLabel lbEquipo5;
    private javax.swing.JLabel lbFiller;
    private javax.swing.JLabel lbJugador;
    private javax.swing.JLabel lbRiot;
    private javax.swing.JLabel lbTituloAdmin;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel lbVersion;
    private javax.swing.JMenu mIntroducirResultado;
    private javax.swing.JMenuItem miAltaDueño;
    private javax.swing.JMenuItem miAltaEquipo;
    private javax.swing.JMenuItem miAltaJugador;
    private javax.swing.JMenuItem miAltaUsuario;
    private javax.swing.JMenuItem miBajaDueño;
    private javax.swing.JMenuItem miBajaEquipo;
    private javax.swing.JMenuItem miBajaJugador;
    private javax.swing.JMenuItem miBajaUsuario;
    private javax.swing.JMenuItem miConsultarDueño;
    private javax.swing.JMenuItem miConsultarDueños;
    private javax.swing.JMenuItem miConsultarEquipo;
    private javax.swing.JMenuItem miConsultarEquipos;
    private javax.swing.JMenuItem miConsultarJugador;
    private javax.swing.JMenuItem miConsultarJugadores;
    private javax.swing.JMenuItem miConsultarUsuario;
    private javax.swing.JMenuItem miConsultarUsuarios;
    private javax.swing.JMenuItem miJornada1;
    private javax.swing.JMenuItem miJornada10;
    private javax.swing.JMenuItem miJornada2;
    private javax.swing.JMenuItem miJornada3;
    private javax.swing.JMenuItem miJornada4;
    private javax.swing.JMenuItem miJornada5;
    private javax.swing.JMenuItem miJornada6;
    private javax.swing.JMenuItem miJornada7;
    private javax.swing.JMenuItem miJornada8;
    private javax.swing.JMenuItem miJornada9;
    private javax.swing.JMenuItem miModificarDueño;
    private javax.swing.JMenuItem miModificarEquipo;
    private javax.swing.JMenuItem miModificarJugador;
    private javax.swing.JMenuItem miModificarUsuario;
    private javax.swing.JMenuItem miVisualizarClasificacion;
    private javax.swing.JMenuItem miVisualizarLiga;
    // End of variables declaration//GEN-END:variables
}
