/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import UML.Dueño;
import javax.swing.JOptionPane;
import jems.JEMS;

/**
 *
 * @author Miguel Barros
 * @author Eric Muñoz
 *
 * @version %I%, %G%
 * @since 1.0
 */
public class V_Dueño extends javax.swing.JFrame {

    /**
     * Creates new form V_Dueño
     */
    public V_Dueño() {
        initComponents();
    }

/**
     * Funcion que al iniciar la ventana recoge el parametro operacion para saber 
     * que tipo de operaciones y realizar los cambios necesarios
     * 
     * 
     * @param operacion (requerido) operacion a realizar
     */
    public V_Dueño(String operacion) {
        initComponents();
        ope = operacion;
        switch (ope) {
            case "modificar":
                tfNombre.setEditable(false);
                tfApellido.setEditable(false);
                tfTelefono.setEditable(false);
                bAceptar.setEnabled(false);
                break;
            case "baja":
                tfNombre.setEditable(false);
                tfApellido.setEditable(false);
                tfTelefono.setEditable(false);
                bAceptar.setEnabled(false);
                break;
            case "alta":
                tfCodigoDueño.setVisible(false);
                bAceptar.setEnabled(false);
                break;
            case "consulta":
                tfNombre.setEditable(false);
                tfApellido.setEditable(false);
                tfTelefono.setEditable(false);
                bAceptar.setEnabled(false);
                break;
        }
    }

    public boolean validarDatos() {
        if (validarNombre(tfNombre.getText()) && validarApellido(tfApellido.getText())) {
            return true;
        } else {
            return false;
        }
    }

    public boolean validarNombre(String nombre) {
        return true;
    }

    public boolean validarApellido(String apellido) {
        return true;
    }
    private static String ope;
    private static Dueño dueño;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAceptar = new javax.swing.JButton();
        bVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfCodigoDueño = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bVolver.setText("Volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo Dueño: ");

        tfCodigoDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoDueñoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Apellido: ");

        jLabel4.setText("Telefono: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(bAceptar)
                        .addGap(71, 71, 71)
                        .addComponent(bVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(tfCodigoDueño)
                            .addComponent(tfNombre)
                            .addComponent(tfApellido))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(tfCodigoDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bVolver))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Funcion para ver que pasa al accionar el boton aceptar en diferentes
     * operaciones.
     *
     * @param evt accionar el boton
     */
    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        try {
            if (validarDatos()) {
                switch (ope) {
                    case "modificar":
                        JEMS.modificarDueño(tfNombre.getText(), tfApellido.getText(), tfTelefono.getText());
                        break;
                    case "alta":
                        JEMS.altaDueño(tfNombre.getText(), tfApellido.getText(), tfTelefono.getText());
                        break;
                    case "baja":
                        JEMS.bajaDueño(Integer.parseInt(tfCodigoDueño.getText()));
                        break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_bAceptarActionPerformed
/**
     * Funcion que al insertar el codigo dueño nos vamos a buscar los datos del 
     * dueño introducido para despues mostrar al cliente los datos de este
     * 
     * 
     * @param evt pulsar enter
     */
    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        ControladorVistas.cerrarVentanaDueño();
    }//GEN-LAST:event_bVolverActionPerformed
/**
     * Funcion que al insertar el codigo dueño nos vamos a buscar los datos del 
     * dueño introducido para despues mostrar al cliente los datos de este
     * 
     * 
     * @param evt pulsar enter
     */
    private void tfCodigoDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoDueñoActionPerformed
        try {
            dueño = JEMS.consultarDueño(Integer.parseInt(tfCodigoDueño.getText()));
            switch (ope) {
                case "modificar":
                    tfNombre.setEditable(true);
                    tfApellido.setEditable(true);
                    tfTelefono.setEditable(true);
                    bAceptar.setEnabled(true);
                    tfNombre.setText(dueño.getNombre());
                    tfApellido.setText(dueño.getApellido());
                    tfTelefono.setText(dueño.getTelefono());
                    tfCodigoDueño.setEditable(false);
                    break;
                case "baja":
                    tfNombre.setEditable(false);
                    tfApellido.setEditable(false);
                    tfTelefono.setEditable(false);
                    bAceptar.setEnabled(true);
                    tfCodigoDueño.setEditable(false);
                    tfNombre.setText(dueño.getNombre());
                    tfApellido.setText(dueño.getApellido());
                    tfTelefono.setText(dueño.getTelefono());
                    break;
                case "consulta":
                    tfNombre.setEditable(false);
                    tfApellido.setEditable(false);
                    tfTelefono.setEditable(false);
                    tfCodigoDueño.setEditable(false);
                    tfNombre.setText(dueño.getNombre());
                    tfApellido.setText(dueño.getApellido());
                    tfTelefono.setText(dueño.getTelefono());
                    break;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getClass());
        }
    }//GEN-LAST:event_tfCodigoDueñoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Dueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Dueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Dueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Dueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Dueño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCodigoDueño;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
