/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import UML.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import jems.JEMS;

/**
 *
 * @author Miguel Barros
 *
 * @version %I%, %G%
 * @since 1.0
 */
public class V_Liga extends javax.swing.JFrame {

    /**
     * Creates new form V_Liga y mostrar en pantalla los datos recogidos desde
     * la base de datos
     *
     * @throws Exception hereda excepciones
     */
    public V_Liga() throws Exception {
        setUndecorated(true);
        initComponents();
        myInitComponents();
        equipos = JEMS.crearListaEquiposOrderPuntuacion();
        liga = JEMS.cogerNombreLiga();
        if (equipos.isEmpty()) {
            tfNombreLiga.setText(liga.getNombre());
        } else {
            tfNombreLiga.setText(liga.getNombre());
            tfEquipo1.setText(equipos.get(0).getNombre());
            tfPuntuacion1.setText(String.valueOf(equipos.get(0).getPuntuacion()));
            tfEquipo2.setText(equipos.get(1).getNombre());
            tfPuntuacion2.setText(String.valueOf(equipos.get(1).getPuntuacion()));
            tfEquipo3.setText(equipos.get(2).getNombre());
            tfPuntuacion3.setText(String.valueOf(equipos.get(2).getPuntuacion()));
            tfEquipo4.setText(equipos.get(3).getNombre());
            tfPuntuacion4.setText(String.valueOf(equipos.get(3).getPuntuacion()));
            tfEquipo5.setText(equipos.get(4).getNombre());
            tfPuntuacion5.setText(String.valueOf(equipos.get(4).getPuntuacion()));
            tfEquipo6.setText(equipos.get(5).getNombre());
            tfPuntuacion6.setText(String.valueOf(equipos.get(5).getPuntuacion()));
        }
    }

    /**
     * Formato de la ventana.
     */
    public void myInitComponents() {
        setSize(1280, 720);
        setLocationRelativeTo(null);
        tfNombreLiga.setBorder(BorderFactory.createCompoundBorder(
                tfNombreLiga.getBorder(),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        tfEquipo1.setBorder(BorderFactory.createCompoundBorder(
                tfEquipo1.getBorder(),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        tfEquipo2.setBorder(BorderFactory.createCompoundBorder(
                tfEquipo2.getBorder(),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        tfEquipo3.setBorder(BorderFactory.createCompoundBorder(
                tfEquipo3.getBorder(),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        tfEquipo4.setBorder(BorderFactory.createCompoundBorder(
                tfEquipo4.getBorder(),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        tfEquipo5.setBorder(BorderFactory.createCompoundBorder(
                tfEquipo5.getBorder(),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        tfEquipo6.setBorder(BorderFactory.createCompoundBorder(
                tfEquipo6.getBorder(),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        tfPuntuacion1.setBorder(BorderFactory.createCompoundBorder(
                tfPuntuacion1.getBorder(),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        tfPuntuacion2.setBorder(BorderFactory.createCompoundBorder(
                tfPuntuacion2.getBorder(),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        tfPuntuacion3.setBorder(BorderFactory.createCompoundBorder(
                tfPuntuacion3.getBorder(),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        tfPuntuacion4.setBorder(BorderFactory.createCompoundBorder(
                tfPuntuacion4.getBorder(),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        tfPuntuacion5.setBorder(BorderFactory.createCompoundBorder(
                tfPuntuacion5.getBorder(),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        tfPuntuacion6.setBorder(BorderFactory.createCompoundBorder(
                tfPuntuacion6.getBorder(),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)));
    }

    /**
     * Creacion de variables
     */
    private static ArrayList<Equipo> equipos;
    private static Liga liga;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLiga = new javax.swing.JLabel();
        lbPosicion = new javax.swing.JLabel();
        lbEquipo = new javax.swing.JLabel();
        lbPuntos = new javax.swing.JLabel();
        tfNombreLiga = new javax.swing.JTextField();
        tfEquipo1 = new javax.swing.JTextField();
        tfEquipo2 = new javax.swing.JTextField();
        tfEquipo3 = new javax.swing.JTextField();
        tfEquipo4 = new javax.swing.JTextField();
        tfEquipo5 = new javax.swing.JTextField();
        tfEquipo6 = new javax.swing.JTextField();
        tfPuntuacion1 = new javax.swing.JTextField();
        tfPuntuacion2 = new javax.swing.JTextField();
        tfPuntuacion3 = new javax.swing.JTextField();
        tfPuntuacion4 = new javax.swing.JTextField();
        tfPuntuacion5 = new javax.swing.JTextField();
        tfPuntuacion6 = new javax.swing.JTextField();
        lbSubtitulo = new javax.swing.JLabel();
        lbPosicion6 = new javax.swing.JLabel();
        lbPosicion1 = new javax.swing.JLabel();
        lbPosicion2 = new javax.swing.JLabel();
        lbPosicion3 = new javax.swing.JLabel();
        lbPosicion4 = new javax.swing.JLabel();
        lbPosicion5 = new javax.swing.JLabel();
        bVolver = new javax.swing.JButton();
        lbRiot = new javax.swing.JLabel();
        lbVersion = new javax.swing.JLabel();
        bSalir = new javax.swing.JButton();
        lbBorde = new javax.swing.JLabel();
        lbFiller = new javax.swing.JLabel();
        lbBackgroundLiga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbLiga.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        lbLiga.setForeground(new java.awt.Color(255, 255, 255));
        lbLiga.setText("Liga");
        getContentPane().add(lbLiga);
        lbLiga.setBounds(650, 190, 60, 40);

        lbPosicion.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        lbPosicion.setForeground(new java.awt.Color(255, 255, 255));
        lbPosicion.setText("Posición");
        getContentPane().add(lbPosicion);
        lbPosicion.setBounds(450, 310, 100, 40);

        lbEquipo.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        lbEquipo.setForeground(new java.awt.Color(255, 255, 255));
        lbEquipo.setText("Equipo");
        getContentPane().add(lbEquipo);
        lbEquipo.setBounds(550, 310, 90, 40);

        lbPuntos.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        lbPuntos.setForeground(new java.awt.Color(255, 255, 255));
        lbPuntos.setText("Puntos");
        getContentPane().add(lbPuntos);
        lbPuntos.setBounds(820, 310, 80, 40);

        tfNombreLiga.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        tfNombreLiga.setForeground(new java.awt.Color(0, 0, 0));
        tfNombreLiga.setEnabled(false);
        getContentPane().add(tfNombreLiga);
        tfNombreLiga.setBounds(600, 230, 160, 30);

        tfEquipo1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        tfEquipo1.setForeground(new java.awt.Color(0, 0, 0));
        tfEquipo1.setEnabled(false);
        getContentPane().add(tfEquipo1);
        tfEquipo1.setBounds(550, 350, 250, 30);

        tfEquipo2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        tfEquipo2.setForeground(new java.awt.Color(0, 0, 0));
        tfEquipo2.setEnabled(false);
        tfEquipo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEquipo2ActionPerformed(evt);
            }
        });
        getContentPane().add(tfEquipo2);
        tfEquipo2.setBounds(550, 390, 250, 30);

        tfEquipo3.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        tfEquipo3.setForeground(new java.awt.Color(0, 0, 0));
        tfEquipo3.setEnabled(false);
        getContentPane().add(tfEquipo3);
        tfEquipo3.setBounds(550, 430, 250, 30);

        tfEquipo4.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        tfEquipo4.setForeground(new java.awt.Color(0, 0, 0));
        tfEquipo4.setEnabled(false);
        getContentPane().add(tfEquipo4);
        tfEquipo4.setBounds(550, 470, 250, 30);

        tfEquipo5.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        tfEquipo5.setForeground(new java.awt.Color(0, 0, 0));
        tfEquipo5.setEnabled(false);
        getContentPane().add(tfEquipo5);
        tfEquipo5.setBounds(550, 510, 250, 30);

        tfEquipo6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        tfEquipo6.setForeground(new java.awt.Color(0, 0, 0));
        tfEquipo6.setEnabled(false);
        getContentPane().add(tfEquipo6);
        tfEquipo6.setBounds(550, 550, 250, 30);

        tfPuntuacion1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        tfPuntuacion1.setForeground(new java.awt.Color(0, 0, 0));
        tfPuntuacion1.setEnabled(false);
        getContentPane().add(tfPuntuacion1);
        tfPuntuacion1.setBounds(820, 350, 60, 30);

        tfPuntuacion2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        tfPuntuacion2.setForeground(new java.awt.Color(0, 0, 0));
        tfPuntuacion2.setEnabled(false);
        getContentPane().add(tfPuntuacion2);
        tfPuntuacion2.setBounds(820, 390, 60, 30);

        tfPuntuacion3.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        tfPuntuacion3.setForeground(new java.awt.Color(0, 0, 0));
        tfPuntuacion3.setEnabled(false);
        getContentPane().add(tfPuntuacion3);
        tfPuntuacion3.setBounds(820, 430, 60, 30);

        tfPuntuacion4.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        tfPuntuacion4.setForeground(new java.awt.Color(0, 0, 0));
        tfPuntuacion4.setEnabled(false);
        getContentPane().add(tfPuntuacion4);
        tfPuntuacion4.setBounds(820, 470, 60, 30);

        tfPuntuacion5.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        tfPuntuacion5.setForeground(new java.awt.Color(0, 0, 0));
        tfPuntuacion5.setEnabled(false);
        getContentPane().add(tfPuntuacion5);
        tfPuntuacion5.setBounds(820, 510, 60, 30);

        tfPuntuacion6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        tfPuntuacion6.setForeground(new java.awt.Color(0, 0, 0));
        tfPuntuacion6.setEnabled(false);
        getContentPane().add(tfPuntuacion6);
        tfPuntuacion6.setBounds(820, 550, 60, 30);

        lbSubtitulo.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        lbSubtitulo.setForeground(new java.awt.Color(86, 88, 149));
        lbSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSubtitulo.setText("LIGA");
        getContentPane().add(lbSubtitulo);
        lbSubtitulo.setBounds(530, 70, 290, 60);

        lbPosicion6.setText("6.");
        getContentPane().add(lbPosicion6);
        lbPosicion6.setBounds(480, 550, 50, 30);

        lbPosicion1.setText("1.");
        getContentPane().add(lbPosicion1);
        lbPosicion1.setBounds(480, 350, 50, 30);

        lbPosicion2.setText("2.");
        getContentPane().add(lbPosicion2);
        lbPosicion2.setBounds(480, 390, 50, 30);

        lbPosicion3.setText("3.");
        getContentPane().add(lbPosicion3);
        lbPosicion3.setBounds(480, 430, 50, 30);

        lbPosicion4.setText("4.");
        getContentPane().add(lbPosicion4);
        lbPosicion4.setBounds(480, 470, 50, 30);

        lbPosicion5.setText("5.");
        getContentPane().add(lbPosicion5);
        lbPosicion5.setBounds(480, 510, 50, 30);

        bVolver.setBackground(new java.awt.Color(86, 88, 149));
        bVolver.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        bVolver.setForeground(new java.awt.Color(255, 255, 255));
        bVolver.setText("VOLVER");
        bVolver.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bVolver.setBorderPainted(false);
        bVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVolver.setFocusPainted(false);
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });
        getContentPane().add(bVolver);
        bVolver.setBounds(590, 630, 170, 30);

        lbRiot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/riotLogo.png"))); // NOI18N
        getContentPane().add(lbRiot);
        lbRiot.setBounds(10, 670, 100, 50);

        lbVersion.setFont(new java.awt.Font("Source Serif Pro Black", 3, 12)); // NOI18N
        lbVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVersion.setText("FINAL_BUILD_V1.0.0");
        getContentPane().add(lbVersion);
        lbVersion.setBounds(1100, 680, 180, 30);

        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/error.png"))); // NOI18N
        bSalir.setBorderPainted(false);
        bSalir.setContentAreaFilled(false);
        bSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSalir.setFocusPainted(false);
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        getContentPane().add(bSalir);
        bSalir.setBounds(1230, 10, 40, 40);

        lbBorde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/blur.png"))); // NOI18N
        lbBorde.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 88, 149), 1, true));
        getContentPane().add(lbBorde);
        lbBorde.setBounds(430, 180, 480, 420);

        lbFiller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/jornada_background.jpg"))); // NOI18N
        getContentPane().add(lbFiller);
        lbFiller.setBounds(0, 0, 1280, 720);

        lbBackgroundLiga.setBackground(new java.awt.Color(13, 9, 32));
        lbBackgroundLiga.setForeground(new java.awt.Color(13, 9, 32));
        lbBackgroundLiga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/background_main_color.png"))); // NOI18N
        getContentPane().add(lbBackgroundLiga);
        lbBackgroundLiga.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Volver a la ventana anterior
     * 
     * @param evt evento al pulsar volver
     */
    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        ControladorVistas.cerrarVentanaLiga();
    }//GEN-LAST:event_bVolverActionPerformed

    /**
     * Salir de la pantalla
     * 
     * @param evt evento al pulsar salir
     */
    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void tfEquipo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEquipo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEquipo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Liga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Liga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Liga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Liga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new V_Liga().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(V_Liga.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSalir;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel lbBackgroundLiga;
    private javax.swing.JLabel lbBorde;
    private javax.swing.JLabel lbEquipo;
    private javax.swing.JLabel lbFiller;
    private javax.swing.JLabel lbLiga;
    private javax.swing.JLabel lbPosicion;
    private javax.swing.JLabel lbPosicion1;
    private javax.swing.JLabel lbPosicion2;
    private javax.swing.JLabel lbPosicion3;
    private javax.swing.JLabel lbPosicion4;
    private javax.swing.JLabel lbPosicion5;
    private javax.swing.JLabel lbPosicion6;
    private javax.swing.JLabel lbPuntos;
    private javax.swing.JLabel lbRiot;
    private javax.swing.JLabel lbSubtitulo;
    private javax.swing.JLabel lbVersion;
    private javax.swing.JTextField tfEquipo1;
    private javax.swing.JTextField tfEquipo2;
    private javax.swing.JTextField tfEquipo3;
    private javax.swing.JTextField tfEquipo4;
    private javax.swing.JTextField tfEquipo5;
    private javax.swing.JTextField tfEquipo6;
    private javax.swing.JTextField tfNombreLiga;
    private javax.swing.JTextField tfPuntuacion1;
    private javax.swing.JTextField tfPuntuacion2;
    private javax.swing.JTextField tfPuntuacion3;
    private javax.swing.JTextField tfPuntuacion4;
    private javax.swing.JTextField tfPuntuacion5;
    private javax.swing.JTextField tfPuntuacion6;
    // End of variables declaration//GEN-END:variables
}
