/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author Jowii
 */
public class V_Mostrar extends javax.swing.JFrame {
    
    /**
     * Creates new form V_Mostrar
     */
    public V_Mostrar() {
        initComponents();
    }
    
    public boolean comprobarCampoVacio(){
        boolean flag = true;
        if(tfCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Introduce el codigo");
            flag = false;
        }        
        return flag;
    }
    
    public boolean comprobarRBSeleccionado(){
        boolean flag = true;
        if(!rbDueño.isSelected() && !rbEquipo.isSelected() && !rbJugador.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona una opcion");
            flag = false;
        }
        return flag;
    }

    public static int getCodigo(){
        int codigo = tfCodigo.getText();
        return codigo;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMostrarDatos = new javax.swing.ButtonGroup();
        bMostrar = new javax.swing.JButton();
        rbJugador = new javax.swing.JRadioButton();
        rbDueño = new javax.swing.JRadioButton();
        rbEquipo = new javax.swing.JRadioButton();
        tfCodigo = new javax.swing.JTextField();
        lbDatos = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bMostrar.setText("Mostrar");
        bMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMostrarActionPerformed(evt);
            }
        });

        bgMostrarDatos.add(rbJugador);
        rbJugador.setText("Jugador");

        bgMostrarDatos.add(rbDueño);
        rbDueño.setText("Dueño");

        bgMostrarDatos.add(rbEquipo);
        rbEquipo.setText("Equipo");

        lbDatos.setText("Codigo");

        lbTitulo.setText("MOSTRAR DATOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(lbDatos)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bMostrar)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rbJugador)
                        .addGap(76, 76, 76)
                        .addComponent(rbEquipo)
                        .addGap(85, 85, 85)
                        .addComponent(rbDueño)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbJugador)
                    .addComponent(rbDueño)
                    .addComponent(rbEquipo))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDatos))
                .addGap(34, 34, 34)
                .addComponent(bMostrar)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMostrarActionPerformed
        if(comprobarCampoVacio() && comprobarRBSeleccionado()){
            if(rbDueño.isSelected()){
                ControladorVistas.mostrarVentanaMostrarDueño();
                ControladorVistas.cerrarVentanaMostrarDueño();
            } else if(rbEquipo.isSelected()) {
                ControladorVistas.mostrarVentanaMostrarEquipo();
                ControladorVistas.cerrarVentanaMostrarEquipo();
            } else if(rbJugador.isSelected()) {
                ControladorVistas.mostrarVentanaMostrarJugador();
                ControladorVistas.cerrarVentanaMostrarJugador();
            }
        }
    }//GEN-LAST:event_bMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Mostrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bMostrar;
    private javax.swing.ButtonGroup bgMostrarDatos;
    private javax.swing.JLabel lbDatos;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JRadioButton rbDueño;
    private javax.swing.JRadioButton rbEquipo;
    private javax.swing.JRadioButton rbJugador;
    private javax.swing.JTextField tfCodigo;
    // End of variables declaration//GEN-END:variables
}
