DROP FUNCTION FUN_CALCULARJUGADORES;
DROP FUNCTION PROC_VERMIEMBROSEQUIPO;
DROP FUNCTION PROC_REF_EQUIPO;

SET SERVEROUTPUT ON

CREATE OR REPLACE FUNCTION FUN_CALCULARJUGADORES--ESTA FUNCION VA A CALCULAR EL NUMERO DE JUGADORES POR EQUIPO
    (EQUIPO_ID IN EQUIPO.COD_EQUIPO%TYPE) --VARIABLE EN LA CUAL GUARDAMOS EL CODIGO DEL EQUIPO
RETURN NUMBER AS
    MIEMBROS NUMBER; --CREACION VARIABLE TIPO NUMBER
BEGIN
    SELECT COUNT(*) INTO MIEMBROS --SELECT PARA CONTAR EL NUMERO DE JUGADORES POR EQUIPO
      FROM JUGADOR
      WHERE  EQUIPO_COD_EQUIPO = EQUIPO_ID;
    RETURN(MIEMBROS); --RETORNAMOS LA VARIABLE NUMBER
END FUN_CALCULARJUGADORES;

/

CREATE OR REPLACE PROCEDURE PROC_VERMIEMBROSEQUIPO --PROCEDIMIENTO CON EL CUAL MOSTRAMOS LOS JUGADORES DE CADA EQUIPO UTILIZANDO
AS --LA FUNCION CREADA ANTERIORMENTE: FUN_CALCULARJUGADORES // EN EL CASO DE QUE NO TENGA JUGADORES MOSTRARA LA CANTIDAD DE 0
    MIEMBROS NUMBER;
BEGIN 
    MIEMBROS := FUN_CALCULARJUGADORES(02); --GUARDAMOS LA FUNCION ANTERIOR EN UNA VARIABLE Y EL CODGIO DEL EQUIPO QUE QUEREMOS MOSTRAR
    DBMS_OUTPUT.PUT_LINE('EL EQUIPO TIENE: '|| MIEMBROS || ' jugadores.' );
END PROC_VERMIEMBROSEQUIPO;

EXECUTE PROC_VERMIEMBROSEQUIPO; --EJECUTAMOS EL PROCEDIMIENTO

/

CREATE OR REPLACE PROCEDURE PROC_REF_EQUIPO --PROCEDIMIENTO PARA MOSTRAR LOS EQUIPOS SU DUEÑO Y LA CANTIDAD DE JUGADORES
  IS
  CURSOR CUR_EQUIPO IS --CURSOR DONDE GUARDAREMOS TODO
    SELECT E.COD_EQUIPO,E.NOMBRE,E.NACIONALIDAD,E.PRESUPUESTO,E.PUNTUACION,E.DUEÑO_COD_CUENTA"CODIGO_DUEÑO",C.NOMBRE"NOMBRE_DUEÑO",NVL(COUNT(J.COD_JUGADOR),0)"NUM_JUGADORES"
    FROM EQUIPO E,DUEÑO D,JUGADOR J,CUENTAS C
    WHERE E.COD_EQUIPO=J.EQUIPO_COD_EQUIPO(+)
    AND E.DUEÑO_COD_CUENTA(+)=D.COD_CUENTA
    AND D.COD_CUENTA(+)=C.COD_CUENTA 
    GROUP BY E.COD_EQUIPO, E.NOMBRE, E.NACIONALIDAD, E.PRESUPUESTO, E.PUNTUACION,E.DUEÑO_COD_CUENTA, C.NOMBRE;
    VREG CUR_EQUIPO%ROWTYPE;
 BEGIN      
  FOR VREG IN CUR_EQUIPO --PARA QUE MUESTRE TODOS LOS EQUIPOS Y NO SOLO 1
    LOOP
      DBMS_OUTPUT.PUT_LINE
        (VREG.COD_EQUIPO||' '||VREG.NOMBRE||' '||VREG.NACIONALIDAD||' '||VREG.PRESUPUESTO||' '||VREG.CODIGO_DUEÑO||' '||VREG.PUNTUACION||' '||VREG.NUM_JUGADORES||' '||VREG.NOMBRE_DUEÑO);
    END LOOP;
END PROC_REF_EQUIPO;

EXECUTE PROC_REF_EQUIPO;