CREATE OR REPLACE FUNCTION FUN_CALCULARJUGADORES
RETURN NUMBER
AS
MIEMBROS NUMBER;
BEGIN
    SELECT COUNT(EQUIPO_COD_EQUIPO) INTO MIEMBROS
      FROM JUGADOR;
RETURN(FUN_CALCULARJUGADORES);
END FUN_CALCULARJUGADORES;






SELECT FUN_CALCULARJUGADORES 
FROM EQUIPO;