CREATE OR REPLACE PROCEDURE PROC_REF_EQUIPO --PROCEDIMIENTO PARA MOSTRAR LOS EQUIPOS SU DUEÑO Y LA CANTIDAD DE JUGADORES
  IS
  CURSOR CURSOR_EQUIPO IS --CURSOR DONDE GUARDAREMOS TODO
    SELECT E.COD_EQUIPO,E.NOMBRE,E.NACIONALIDAD,E.PRESUPUESTO,E.PUNTUACION,E.DUEÑO_COD_CUENTA"CODIGO_DUEÑO",C.NOMBRE"NOMBRE_DUEÑO",NVL(COUNT(J.COD_JUGADOR),0)"NUM_JUGADORES"
    FROM EQUIPO E,DUEÑO D,JUGADOR J,CUENTAS C
    WHERE E.COD_EQUIPO=J.EQUIPO_COD_EQUIPO(+)
    AND E.DUEÑO_COD_CUENTA(+)=D.COD_CUENTA
    AND D.COD_CUENTA(+)=C.COD_CUENTA 
    GROUP BY E.COD_EQUIPO, E.NOMBRE, E.NACIONALIDAD, E.PRESUPUESTO, E.PUNTUACION,E.DUEÑO_COD_CUENTA, C.NOMBRE;
    VREG CURSOR_EQUIPO%ROWTYPE;
 BEGIN      
  FOR VREG IN CURSOR_EQUIPO --PARA QUE MUESTRE TODOS LOS EQUIPOS Y NO SOLO 1
    LOOP
      DBMS_OUTPUT.PUT_LINE
        (VREG.COD_EQUIPO||' '||VREG.NOMBRE||' '||VREG.NACIONALIDAD||' '||VREG.PRESUPUESTO||' '||VREG.CODIGO_DUEÑO||' '||VREG.PUNTUACION||' '||VREG.NUM_JUGADORES||' '||VREG.NOMBRE_DUEÑO);
    END LOOP;
END PROC_REF_EQUIPO;

EXECUTE PROC_REF_EQUIPO;