CREATE OR REPLACE PROCEDURE PROC_REF_EQUIPO --PROCEDIMIENTO PARA MOSTRAR LOS EQUIPOS SU DUEÑO Y LA CANTIDAD DE JUGADORES
(CUR_EQUIPO OUT SYS_REFCURSOR)
  IS
  CURSOR CUR_EQUIPO IS --CURSOR DONDE GUARDAREMOS TODO
    SELECT E.COD_EQUIPO,E.NOMBRE,E.NACIONALIDAD,E.PRESUPUESTO,E.PUNTUACION,E.DUEÑO_COD_CUENTA"CODIGO_DUEÑO",C.NOMBRE"NOMBRE_DUEÑO",NVL(COUNT(J.COD_JUGADOR),0)"NUM_JUGADORES"
    FROM EQUIPO E,DUEÑO D,JUGADOR J,CUENTAS C
    WHERE E.COD_EQUIPO=J.EQUIPO_COD_EQUIPO(+)
    AND E.DUEÑO_COD_CUENTA(+)=D.COD_CUENTA
    AND D.COD_CUENTA(+)=C.COD_CUENTA 
    GROUP BY E.COD_EQUIPO, E.NOMBRE, E.NACIONALIDAD, E.PRESUPUESTO, E.PUNTUACION,E.DUEÑO_COD_CUENTA, C.NOMBRE;
    VREG CUR_EQUIPO%ROWTYPE;
 BEGIN      
  FOR VREG IN CUR_EQUIPO --PARA QUE MUESTRE TODOS LOS EQUIPOS Y NO SOLO 1
    LOOP
      DBMS_OUTPUT.PUT_LINE
        (VREG.COD_EQUIPO||' '||VREG.NOMBRE||' '||VREG.NACIONALIDAD||' '||VREG.PRESUPUESTO||' '||VREG.CODIGO_DUEÑO||' '||VREG.PUNTUACION||' '||VREG.NUM_JUGADORES||' '||VREG.NOMBRE_DUEÑO);
    END LOOP;
END PROC_REF_EQUIPO;

/

CREATE OR REPLACE PROCEDURE PROC_REF_EQUIPO --PROCEDIMIENTO PARA MOSTRAR LOS EQUIPOS SU DUEÑO Y LA CANTIDAD DE JUGADORES
(CUR_EQUIPO OUT SYS_REFCURSOR)
  IS
 BEGIN      
  OPEN CUR_EQUIPO FOR
    SELECT E.COD_EQUIPO,E.NOMBRE,E.NACIONALIDAD,E.PRESUPUESTO,E.PUNTUACION,E.DUEÑO_COD_CUENTA"CODIGO_DUEÑO",C.NOMBRE"NOMBRE_DUEÑO",NVL(COUNT(J.COD_JUGADOR),0)"NUM_JUGADORES"
    FROM EQUIPO E,DUEÑO D,JUGADOR J,CUENTAS C
    WHERE E.COD_EQUIPO=J.EQUIPO_COD_EQUIPO(+)
    AND E.DUEÑO_COD_CUENTA(+)=D.COD_CUENTA
    AND D.COD_CUENTA(+)=C.COD_CUENTA 
    GROUP BY E.COD_EQUIPO, E.NOMBRE, E.NACIONALIDAD, E.PRESUPUESTO, E.PUNTUACION,E.DUEÑO_COD_CUENTA, C.NOMBRE;
END PROC_REF_EQUIPO;

DECLARE 
CUR_EQUIPO SYS_REFCURSOR;
V_COD_EQUIPO EQUIPO.COD_EQUIPO%TYPE;
V_NOMBRE EQUIPO.NOMBRE%TYPE;
V_NACIONALIDAD EQUIPO.NACIONALIDAD%TYPE;
V_PRESUPUESTO EQUIPO.PRESUPUESTO%TYPE;
V_PUNTUACION EQUIPO.PRESUPUESTO%TYPE;
V_CODIGO_DUEÑO EQUIPO.DUEÑO_COD_CUENTA%TYPE;
V_NOMBRE_DUEÑO CUENTA.NOMBRE%TYPE;
V_NUM_JUGADORES NUMBER;
BEGIN
    PROC_REF_EQUIPO  
    (CUR_EQUIPO);
  LOOP
  FETCH CUR_EQUIPO INTO V_COD_EQUIPO,V_NOMBRE,V_NACIONALIDAD,V_PRESUPUESTO,V_PUNTUACION,V_CODIGO_DUEÑO,V_NOMBRE_DUEÑO,V_NUM_JUGADORES;
  EXIT WHEN P_CURSOR_LISTA%NOTFOUND;
  DBMS_OUTPUT.PUT_LINE
        (V_COD_EQUIPO||' '||V_NOMBRE||' '||V_NACIONALIDAD||' '||V_PRESUPUESTO||' '||V_CODIGO_DUEÑO||' '||V_PUNTUACION||' '||V_NUM_JUGADORES||' '||V_NOMBRE_DUEÑO);
  END LOOP;
END;