
DROP PROCEDURE GENERAR_CALENDARIO;

CREATE OR REPLACE PROCEDURE GENERAR_CALENDARIO(FECHA_INICIO_LIGA DATE)
IS 
V_INICIO_JORNADA DATE;
V_FIN_JORNADA DATE;
V_FIN_JORNADA_2 DATE;
V_FECHA_INICIO_JORNADA_2 DATE;
V_CONTADOR NUMBER := 02;
BEGIN 
    IF FECHA_INICIO_LIGA < SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20006,'LA LIGA NO PUEDE EMPEZAR ANTES DEL DIA DE HOY');
    END IF;
    INSERT INTO LIGA (FECHA_INICIO,COD_LIGA,NOMBRE,ESTADO) VALUES(FECHA_INICIO_LIGA,01,'HOLA',0); --INSERTAMOS LA FECHA DE INICIO DE LA LIGA
    INSERT INTO JORNADA (FECHA_INICIO,COD_JORNADA,LIGA_COD_LIGA) VALUES(FECHA_INICIO_LIGA,01,01); --INSERTAMOS LA PRIMERA JORANADA
    V_FIN_JORNADA := FECHA_INICIO_LIGA + 3; -- EL FINAL DE JORNADA SERA 3 DIAS DESPUES DEL INICO DE LA JORNADA
    V_INICIO_JORNADA := FECHA_INICIO_LIGA + 7; --LA SIGUIENTE JORNADA SERA 7 DIAS DESPUES DEL FINAL DE LA ANTERIOR JORNADA
    UPDATE JORNADA SET FECHA_FIN = V_FIN_JORNADA WHERE FECHA_INICIO = FECHA_INICIO_LIGA; --HACEMOS UPDATE DEL FIN DE LA JORNADA DEL INICIO DE LA JORNADA QUE VACIA
            DBMS_OUTPUT.PUT_LINE('INICIO JORNADA: '||V_INICIO_JORNADA||' FIN JORNADA: '||V_FIN_JORNADA); --SACAMOS POR PANTALLA EL INICIO Y FINAL DE CADA JORNADA
    LOOP
     INSERT INTO JORNADA (FECHA_INICIO,COD_JORNADA,LIGA_COD_LIGA) VALUES(V_INICIO_JORNADA,V_CONTADOR,01); --INSERTAMOS LA JORNADA X
     V_FIN_JORNADA_2 := V_INICIO_JORNADA + 3; -- EL FINAL DE JORNADA SERA 3 DIAS DESPUES DEL INICO DE LA JORNADA
     UPDATE JORNADA SET FECHA_FIN = V_FIN_JORNADA_2 WHERE FECHA_INICIO = V_INICIO_JORNADA; --HACEMOS UPDATE DEL FIN DE LA JORNADA DEL INICIO DE LA JORNADA QUE VACIA
      V_FECHA_INICIO_JORNADA_2:= V_INICIO_JORNADA + 7; --LA SIGUIENTE JORNADA SERA 7 DIAS DESPUES DEL FINAL DE LA ANTERIOR JORNADA
        DBMS_OUTPUT.PUT_LINE('INICIO JORNADA: '||V_INICIO_JORNADA||' FIN JORNADA: '||V_FIN_JORNADA); --SACAMOS POR PANTALLA EL INICIO Y FINAL DE CADA JORNADA
	V_CONTADOR := V_CONTADOR + 1; --SUMAREMOS UNO A NUESTRO CONTADOR HASTA 12, QUE SON LAS JORNADAS QUE HABRA 
	EXIT WHEN V_CONTADOR = 12; --SALDREMOS DEL LOOP CUANDO EL CONTADOR ESTE EN 12
    END LOOP;
    UPDATE LIGA SET FECHA_FIN = V_FIN_JORNADA_2; --HACEMOS UPDATE DEL FIN DE LA LIGA QUE ESTA VACIA
END GENERAR_CALENDARIO;

EXECUTE GENERAR_CALENDARIO(SYSDATE); 

SELECT * FROM JORNADA;
SELECT * FROM LIGA;

DELETE FROM JORNADA;
DELETE FROM LIGA;