
--PROBAR PROCEDIMIENTO PROC_VERMIEMBROSEQUIPO

DECLARE
P_EQUIPO_ID EQUIPO.COD_EQUIPO%TYPE:=01;
MIEMBROS NUMBER;
BEGIN 
    PROC_VERMIEMBROSEQUIPO
    (P_EQUIPO, MIEMBROS);
    DBMS_OUTPUT.PUT_LINE('EL EQUIPO TIENE: '|| MIEMBROS || ' jugadores.' );
END;

/

--PROBAR EL PROCEDIMIENTO PROC_REF_EQUIPO

DECLARE 
    CUR_EQUIPO SYS_REFCURSOR;
    V_COD_EQUIPO EQUIPO.COD_EQUIPO%TYPE;
    V_NOMBRE EQUIPO.NOMBRE%TYPE;
    V_NACIONALIDAD EQUIPO.NACIONALIDAD%TYPE;
    V_PRESUPUESTO EQUIPO.PRESUPUESTO%TYPE;
    V_PUNTUACION EQUIPO.PRESUPUESTO%TYPE;
    V_CODIGO_DUE�O EQUIPO.DUE�O_COD_CUENTA%TYPE;
    V_NOMBRE_DUE�O CUENTAS.NOMBRE%TYPE;
    V_NUM_JUGADORES NUMBER;
BEGIN
    PROC_REF_EQUIPO(CUR_EQUIPO);
    LOOP
      FETCH CUR_EQUIPO INTO V_COD_EQUIPO,V_NOMBRE,V_NACIONALIDAD,V_PRESUPUESTO,V_PUNTUACION,V_CODIGO_DUE�O,V_NOMBRE_DUE�O,V_NUM_JUGADORES;
      EXIT WHEN CUR_EQUIPO%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE
            (V_COD_EQUIPO||' '||V_NOMBRE||' '||V_NACIONALIDAD||' '||V_PRESUPUESTO||' '||V_CODIGO_DUE�O||' '||V_PUNTUACION||' '||V_NUM_JUGADORES||' '||V_NOMBRE_DUE�O);
    END LOOP;
END;

/

--COMPROBADORES DE QUE SE HA CREADO LA LIGA VACIA

EXECUTE GENERAR_CALENDARIO(SYSDATE); 

SELECT * FROM JORNADA;
SELECT * FROM LIGA;