

INSERT INTO USUARIO (USUARIO, CONTRASEÑA)VALUES ('USER', 'USER');

INSERT INTO ADMINISTRADOR (USUARIO, CONTRASEÑA)VALUES ('a', 'a');
INSERT INTO ADMINISTRADOR (USUARIO, CONTRASEÑA)VALUES ('A', 'A');


INSERT INTO DUEÑO (NOMBRE,APELLIDO,TELEFONO) VALUES ('MICHAEL' , 'WILHOIT',673910207);
INSERT INTO DUEÑO (NOMBRE,APELLIDO,TELEFONO) VALUES ('GEORGE', 'GRIFFIN',781201201);
INSERT INTO DUEÑO (NOMBRE,APELLIDO,TELEFONO) VALUES ('DEBBIE', 'HAWKINS',682912022);
INSERT INTO DUEÑO (NOMBRE,APELLIDO,TELEFONO) VALUES ('LARRY', 'BONDS',832723923);
INSERT INTO DUEÑO (NOMBRE,APELLIDO,TELEFONO) VALUES ('DARYL', 'CHARLES',743934034);
INSERT INTO DUEÑO (NOMBRE,APELLIDO,TELEFONO) VALUES ('JOHN', 'FLAGG',672392393);
INSERT INTO DUEÑO (NOMBRE,APELLIDO,TELEFONO) VALUES ('WILLIAM', 'COOPER',812912012);
INSERT INTO DUEÑO (NOMBRE,APELLIDO,TELEFONO) VALUES ('JORDAN', 'HARRIS',721912021);


INSERT INTO EQUIPO (NOMBRE, NACIONALIDAD, PRESUPUESTO, DUEÑO_COD_DUEÑO, PUNTUACION)VALUES('FNATIC', 'REINO UNIDO', 180000, 01, 0);
INSERT INTO EQUIPO (NOMBRE, NACIONALIDAD, PRESUPUESTO, DUEÑO_COD_DUEÑO, PUNTUACION)VALUES('G2 ESPORTS', 'ESPAï¿½A', 190000, 02, 0);
INSERT INTO EQUIPO (NOMBRE, NACIONALIDAD, PRESUPUESTO, DUEÑO_COD_DUEÑO, PUNTUACION)VALUES('ORIGEN', 'ESPAï¿½A', 140000, 03, 0);
INSERT INTO EQUIPO (NOMBRE, NACIONALIDAD, PRESUPUESTO, DUEÑO_COD_DUEÑO, PUNTUACION)VALUES('SK GAMING', 'ALEMANIA', 155000, 04,  0);
INSERT INTO EQUIPO (NOMBRE, NACIONALIDAD, PRESUPUESTO, DUEÑO_COD_DUEÑO, PUNTUACION)VALUES('SPLYCE', 'ESTADOS UNIDOS', 150000, 05, 0);
INSERT INTO EQUIPO (NOMBRE, NACIONALIDAD, PRESUPUESTO, DUEÑO_COD_DUEÑO, PUNTUACION)VALUES('TEAM VITALITY', 'FRANCIA', 140000, 06, 0);




--FNATIC
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('GABRIEL', 'RAU', 'BWIPO', 1000, 'BELGICA', 'CONTRATADO', 684939291, 01);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('MADS', 'BROCK-PEDERSEN', 'BROXAH', 1000, 'DINAMARCA', 'CONTRATADO', 683010193, 01);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('TIM', 'LIPOVSEK', 'NEMESIS', 1000, 'ESLOVENIA', 'CONTRATADO', 683910291, 01);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('MARTIN', 'LARSON', 'REKKLES', 1000, 'SUECIA', 'CONTRATADO', 743818282, 01);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('ZDRAVETS', 'LLIEV', 'HYLISSANG', 1000, 'BULGARIA', 'CONTRATADO', 748182930, 01);


--G2
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('MARTIN', 'HANSEN', 'WUNDER', 1000, 'DINAMARCA', 'CONTRATADO', 682039192, 02);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('MARCIN', 'JANKOWSKI', 'JANKOS', 1000, 'POLONIA', 'CONTRATADO', 683919203, 02);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('RASMUS', 'WINTHER', 'CAPS', 1000, 'DINAMARCA', 'CONTRATADO', 683920192, 02);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('LUKA', 'PERKOVI?', 'PERKZ', 1000, 'CROACIA', 'CONTRATADO', 683920174, 02);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('MIHAEL', 'MEHLE', 'MIKYX', 1000, 'ESLOVENIA', 'CONTRATADO', 628301022, 02);

--ORIGEN
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('BARNEY', 'MORRIS', 'ALPHARI', 1000, 'REINO UNIDO', 'CONTRATADO', 683919203, 03);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('JONAS', 'ANDERSEN', 'KOLD', 1000, 'DINAMARCA', 'CONTRATADO', 683920394, 03);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('ERLEND', 'VTEVIK', 'NUKEDUCK', 1000, 'NORUEGA', 'CONTRATADO', 928392930, 03);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('PATRIK', 'Jï¿½R?', 'PATRIK', 1000, 'REPUBLICA CHECA', 'CONTRATADO', 937481828, 03);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('ALFONSO', 'AGUIRRE', 'MITHY', 1000, 'ESPAï¿½A', 'CONTRATADO', 928371828, 03);

--SK GAMING
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('JORGE', 'CASANOVAS', 'WERLYB', 1000, 'ESPAï¿½A', 'CONTRATADO', 928374618, 04);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('OSKAR', 'BODEREK', 'SELFMADE', 1000, 'POLONIA', 'CONTRATADO', 849381729, 04);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('CHOI', 'JUN-SIK', 'PIREAN', 1000, 'COREA', 'CONTRATADO', 673912123, 04);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('JUï¿½', 'MARUï¿½I?', 'CROWNSHOT', 1000, 'ESLOVENIA', 'CONTRATADO', 839283912, 04);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('HAN', 'MIN-KOOK', 'DREAMS', 1000, 'COREA', 'CONTRATADO', 728394819, 04);

--SPLYCE
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('ANDREI', 'POPA', 'OROME', 1000, 'RUMANIA', 'CONTRATADO', 918281231, 05);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('TAMï¿½S', 'KISS', 'VIZICSACSI', 1000, 'HUNGRIA', 'CONTRATADO', 812831231, 05);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('ANDREI', 'DRAGOMIR', 'XERXE', 1000, 'RUMANIA', 'CONTRATADO', 912831012, 05);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('MAREK', 'BRï¿½ZDA', 'HUMANOID', 1000, 'REPUBLICA CHECA', 'CONTRATADO', 712801281, 05);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('KASPER', 'KOBBERUP', 'KOBBE', 1000, 'DINAMARCA', 'CONTRATADO', 912812012, 05);

--TEAM VITALITY
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('LUCAS', 'SIMON-MESLET', 'CABOCHARD', 1000, 'FRANCIA', 'CONTRATADO', 681291201, 06);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('LEE', 'JAE-HA', 'MOWGLI', 1000, 'COREA', 'CONTRATADO', 712912012, 06);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('DANIELE', 'DI MAURO', 'JIZUKE', 1000, 'ITALIA', 'CONTRATADO', 723932011, 06);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('AMADEU', 'CARVALHO', 'ATTILA', 1000, 'PORTUGAL', 'CONTRATADO', 612812012, 06);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('JAKUB', 'SKURZY?SKI', 'JACTROLL', 1000, 'POLONIA', 'CONTRATADO', 782910291, 06);

-- SIN CONTRATO
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('LEE', 'SANG-HO', 'EFFORT', 1000, 'COREA', 'VACANTE', 783910293, NULL);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('KIM', 'DO-YEONG', 'DORAON', 1000, 'COREA', 'VACANTE', 671212882, NULL);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('DAVID', 'ROBERSON', 'COP', 1000, 'ESTADOS UNIDOS', 'VACANTE', 672829102, NULL);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('MATYï¿½ï¿½', 'ORSï¿½G', 'CARZZY', 1000, 'REPUBLICA CHECA', 'VACANTE', 928291281, NULL);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('DEIVYDAS', 'PLIKAITIS', 'AGENTAS', 1000, 'LITUANIA', 'VACANTE', 712812912, NULL);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('FELIX', 'BOSTRï¿½M', 'MAGIFELIX', 1000, 'SUECIA', 'VACANTE', 912012912, NULL);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('TONI', 'SABALI?', 'SACRE', 1000, 'CROACIA', 'VACANTE', 612947538, NULL);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('PH?M', 'MINH', 'ZEROS', 1000, 'VIETNAM', 'VACANTE', 712912012, NULL);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('HOï¿½NG', 'TI?N', 'MELIODAS', 1000, 'VIETNAM', 'VACANTE', 829310122, NULL);
INSERT INTO JUGADOR (NOMBRE, APELLIDO, NICKNAME, SUELDO, NACIONALIDAD, ESTADO, TELEFONO, EQUIPO_COD_EQUIPO)
VALUES ('ILYA', 'MAKAVCHUK', 'GADGET', 1000, 'BIELORRUSIA', 'VACANTE', 693012912, NULL);

commit;
