DROP TABLE ADMINISTRADOR CASCADE CONSTRAINTS;
DROP TABLE DUEÑO CASCADE CONSTRAINTS;
DROP TABLE EQUIPO CASCADE CONSTRAINTS;
DROP TABLE JORNADA CASCADE CONSTRAINTS;
DROP TABLE JUGADOR CASCADE CONSTRAINTS;
DROP TABLE LIGA CASCADE CONSTRAINTS;
DROP TABLE PARTICIPAR CASCADE CONSTRAINTS;
DROP TABLE PARTIDO CASCADE CONSTRAINTS;
DROP TABLE RESULTADO CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;


CREATE TABLE ADMINISTRADOR (
    CODIGO_ADMINISTRADOR   NUMBER(4) NOT NULL,
    USUARIO                VARCHAR2(20) NOT NULL,
    CONTRASEÑA             VARCHAR2(20) NOT NULL,
    CONSTRAINT ADMINISTRADOR_PK PRIMARY KEY ( CODIGO_ADMINISTRADOR )
);

CREATE TABLE USUARIO (
    CODIGO_USUARIO   NUMBER(4) NOT NULL,
    USUARIO          VARCHAR2(20) NOT NULL,
    CONTRASEÑA       VARCHAR2(20) NOT NULL,
    CONSTRAINT USUARIO_PK PRIMARY KEY ( CODIGO_USUARIO )
);


CREATE TABLE DUEÑO (
    CODIGO_DUEÑO     NUMBER(4) NOT NULL,
    NOMBRE_DUEÑO     VARCHAR2(20) NOT NULL,
    APELLIDO_DUEÑO   VARCHAR2(20) NOT NULL,
    CONSTRAINT DUEÑO_PK PRIMARY KEY ( CODIGO_DUEÑO )
);


CREATE TABLE EQUIPO (
    CODIGO_EQUIPO        NUMBER(4) NOT NULL,
    NOMBRE_EQUIPO        VARCHAR2(20) NOT NULL,
    PRESUPUESTO          NUMBER(6) NOT NULL,
    LOCALIDAD            VARCHAR2(20) NOT NULL,
    DUEÑO_CODIGO_DUEÑO   NUMBER(4) NOT NULL,
    CONSTRAINT EQUIPO_DUEÑO_FK FOREIGN KEY ( DUEÑO_CODIGO_DUEÑO )
        REFERENCES DUEÑO ( CODIGO_DUEÑO ),
    CONSTRAINT EQUIPO_PK PRIMARY KEY ( CODIGO_EQUIPO )
);

CREATE TABLE JUGADOR (
    CODIGO_JUGADOR         NUMBER(4) NOT NULL,
    NOMBRE_JUGADOR         VARCHAR2(20) NOT NULL,
    APELLIDO_JUGADOR       VARCHAR2(20) NOT NULL,
    NICKNAME               VARCHAR2(20) NOT NULL,
    SUELDO                 NUMBER(6) NOT NULL,
    NACIONALIDAD           VARCHAR2(20) NOT NULL,
    ESTADO                 VARCHAR2(20) NOT NULL,
    EQUIPO_CODIGO_EQUIPO   NUMBER(4) NOT NULL,
    CONSTRAINT JUGADOR_PK PRIMARY KEY ( CODIGO_JUGADOR ),
    CONSTRAINT JUGADOR_EQUIPO_FK FOREIGN KEY ( EQUIPO_CODIGO_EQUIPO )
        REFERENCES EQUIPO ( CODIGO_EQUIPO )
);

CREATE TABLE JORNADA (
    CODIGO_JORNADA   NUMBER(4) NOT NULL,
    FECHA            DATE NOT NULL,
    CONSTRAINT JORNADA_PK PRIMARY KEY ( CODIGO_JORNADA )
);

CREATE TABLE PARTICIPAR (
    EQUIPO_CODIGO_EQUIPO     NUMBER(4) NOT NULL,
    JORNADA_CODIGO_JORNADA   NUMBER(4) NOT NULL,
    CONSTRAINT PARTICIPAR_PK PRIMARY KEY ( EQUIPO_CODIGO_EQUIPO, JORNADA_CODIGO_JORNADA ),
    CONSTRAINT PARTICIPAR_EQUIPO_FK FOREIGN KEY ( EQUIPO_CODIGO_EQUIPO )
        REFERENCES EQUIPO ( CODIGO_EQUIPO ),
    CONSTRAINT PARTICIPAR_JORNADA_FK FOREIGN KEY ( JORNADA_CODIGO_JORNADA )
        REFERENCES JORNADA ( CODIGO_JORNADA )
);


CREATE TABLE LIGA (
    CODIGO_LIGA NUMBER(4) NOT NULL,
    CONSTRAINT LIGA_PK PRIMARY KEY ( CODIGO_LIGA )
);

CREATE TABLE RESULTADO (
    CODIGO_RESULTADO         NUMBER(4) NOT NULL,
    PUNTUACION               NUMBER(3) NOT NULL,
    PARTIDO_CODIGO_PARTIDO   NUMBER(4) NOT NULL,
    LIGA_CODIGO_LIGA         NUMBER(4) NOT NULL,
    CONSTRAINT RESULTADO_PK PRIMARY KEY ( CODIGO_RESULTADO ),
    CONSTRAINT RESULTADO_LIGA_FK FOREIGN KEY ( LIGA_CODIGO_LIGA )
        REFERENCES LIGA ( CODIGO_LIGA )
);

CREATE TABLE PARTIDO (
    CODIGO_PARTIDO               NUMBER(4) NOT NULL,
    EQUIPOA                      VARCHAR2(20) NOT NULL,
    EQUIPOB                      VARCHAR2(20) NOT NULL,
    JORNADA_CODIGO_JORNADA       NUMBER(4) NOT NULL,
    RESULTADO_CODIGO_RESULTADO   NUMBER(4) NOT NULL,
    CONSTRAINT PARTIDO_PK PRIMARY KEY ( CODIGO_PARTIDO ),
    CONSTRAINT PARTIDO_JORNADA_FK FOREIGN KEY ( JORNADA_CODIGO_JORNADA )
        REFERENCES JORNADA ( CODIGO_JORNADA )
);

ALTER TABLE RESULTADO ADD CONSTRAINT RESULTADO_PARTIDO_FK FOREIGN KEY ( PARTIDO_CODIGO_PARTIDO )
        REFERENCES PARTIDO ( CODIGO_PARTIDO );
        
ALTER TABLE PARTIDO ADD CONSTRAINT PARTIDO_RESULTADO_FK FOREIGN KEY ( RESULTADO_CODIGO_RESULTADO )
        REFERENCES RESULTADO ( CODIGO_RESULTADO );
        

CREATE UNIQUE INDEX PARTIDO__IDX ON
    PARTIDO (
        RESULTADO_CODIGO_RESULTADO
    ASC );


CREATE UNIQUE INDEX RESULTADO__IDX ON
    RESULTADO (
        PARTIDO_CODIGO_PARTIDO
    ASC );
