DROP SEQUENCE AUTO_COD_JUG_SEQ;
DROP SEQUENCE AUTO_COD_CUENTA_SEQ;
DROP SEQUENCE AUTO_COD_EQUIPO_SEQ;
DROP SEQUENCE AUTO_COD_JORNADA_SEQ;

CREATE SEQUENCE AUTO_COD_JUG_SEQ 
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 999
NOCYCLE;

CREATE SEQUENCE AUTO_COD_CUENTA_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 999
NOCYCLE;

CREATE SEQUENCE AUTO_COD_EQUIPO_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 999
NOCYCLE;

CREATE SEQUENCE AUTO_COD_JORNADA_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 999
NOCYCLE;