
CREATE SEQUENCE AUTOINCREMENTAL_CODIGO_JUGADOR_SEQ 
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 999
NOCYCLE;

CREATE SEQUENCE AUTOINCREMENTAL_CODIGO_CUENTA_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 999
NOCYCLE;

CREATE SEQUENCE AUTOINCREMENTAL_CODIGO_EQUIPO_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 999
NOCYCLE;

CREATE SEQUENCE AUTOINCREMENTAL_CODIGO_JORNADA_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 999
NOCYCLE;