
CREATE OR REPLACE TRIGGER TRIG_SAL_MAX_EQUIPO --CREAR TRIGGER PARA EL SALARIO MAXIMO EQUIPO
BEFORE INSERT OR UPDATE ON EQUIPO FOR EACH ROW
DECLARE
SALARIO_MAX NUMBER(6):=200.000;
ERROR_SAL_MAX EXCEPTION;--ERROR PROPIO DEL SALARIO MAXIMO DE EQUIPO
BEGIN
    IF INSERTING THEN
        IF PRESUPUESTO>SALARIO_MAX THEN --SI EL PRESUPUESTO ES MAYOR QUE EL SARAIO MAXIMO
         RAISE ERROR_SAL_MAX;--EJECUTAR ERROR PROPIO
        END IF;
    END IF;
    IF UPDATIONG THEN
         IF :NEW.PRESUPUESTO>SALARIO_MAX THEN
         RAISE ERROR_SAL_MAX;
        END IF;
    END IF;    
END TRIG_SAL_MAX_EQUIPO;