CREATE OR REPLACE TRIGGER TRIG_NO_MODIFICAR_ESTRUCTURA_EQUIPO
BEFORE INSERT OR UPDATE ON EQUIPO --ANTES DE INSERTAR EN EQUIPO
FOR EACH ROW
BEGIN 
    IF LIGA.estado = 1 THEN --SI EL ESTADO DE LA LIGA ESTA CERRADO
        RAISE_APPLICATION_ERROR(-20001,'NO SE PUEDE MODFICAR LA ESTRUCTURA DE EQUIPOS'); --SE LANZARA UN RAISE APPLICATION ERROR QUE NO DEJARA HACERLA
    END IF;
END TRIG_NO_MODIFICAR_ESTRUCTURA_EQUIPO;

CREATE OR REPLACE TRIGGER TRIG_NO_MODIFICAR_ESTRUCTURA_JUGADORES
BEFORE INSERT OR UPDATE ON JUGADOR --ANTES DE INSERTAR EN EQUIPOS 
FOR EACH ROW
BEGIN 
    IF LIGA.estado = 1 THEN --SI EL ESTADO DE LA LIGA ESTA CERRADO
        RAISE_APPLICATION_ERROR(-20001,'NO SE PUEDE MODFICAR LA ESTRUCTURA DE JUGADORES'); --SE LANZARA UN RAISE APPLICATION ERROR QUE NO DEJARA HACERLA
    END IF;
END TRIG_NO_MODIFICAR_ESTRUCTURA_JUGADORES;