CREATE OR REPLACE TRIGGER TRIG_SAL_MAX_EQUIPO --CREAR TRIGGER PARA EL SALARIO MAXIMO EQUIPO
BEFORE INSERT OR UPDATE ON EQUIPO FOR EACH ROW
DECLARE
    SALARIO_MAX NUMBER(6):=200000;
BEGIN
    PAQUETE_MUTANTE.SALMAX:=:NEW.PRESUPUESTO;
    IF PAQUETE_MUTANTE.SALMAX>SALARIO_MAX THEN --SI EL PRESUPUESTO ES MAYOR QUE EL SALARIO MAXIMO
        RAISE_APPLICATION_ERROR(-20002,'PRESUPUESTO EQUIPO MAYOR QUE 200.000.');--EJECUTAR ERROR
    END IF;  
END TRIG_SAL_MAX_EQUIPO;