CREATE OR REPLACE TRIGGER TRIG_NO_JUGADORES --TRIGGER QUE COMPRUEBA QUE NO HAYA EQUIPOS SIN JUGADORES ANTES DE CREAR LA LIGA
BEFORE INSERT OR UPDATE ON LIGA 
FOR EACH ROW
DECLARE
V_CANTIDAD NUMBER;
CURSOR CUR_NUM_JUG_EQUIPO IS --CREAR CURSOR PARA BUSCAR NUMERO DE JUGADORES EN UN EQUIPO
  SELECT NVL(COUNT(COD_JUGADOR), 0) "NUM_JUGADORES" INTO V_CANTIDAD
  FROM JUGADOR
  GROUP BY EQUIPO_COD_EQUIPO;
  VREG2 CUR_NUM_JUG_EQUIPO%ROWTYPE; --GUARDAR CURSOR EN VARIABLE

BEGIN
  FOR VREG2 IN CUR_NUM_JUG_EQUIPO --MIRAR NUMERO DE JUGADORES EN TODOS LOS EQUIPOS 
    LOOP
      IF VREG2.NUM_JUGADORES = 0 THEN --COMPROBAR NUMERO DE JUGADORES
      RAISE_APPLICATION_ERROR (-20006,'No hay jugadores en el equipo'); -- ACTIVA EL ERROR
      ELSE 
      UPDATE LIGA SET ESTADO = 1; --SI ESTA TODO EN ORDEN LA LIGA EMPIEZA
      END IF;
    END LOOP;
END TRIG_NO_JUGADORES;

