
CREATE OR REPLACE TRIGGER TRIG_SAL_MAX_EQUIPO --CREAR TRIGGER PARA EL SALARIO MAXIMO EQUIPO
BEFORE INSERT OR UPDATE ON EQUIPO FOR EACH ROW
DECLARE
SALARIO_MAX NUMBER(6):=200000;
ERROR_SAL_MAX EXCEPTION;--ERROR PROPIO DEL SALARIO MAXIMO DE EQUIPO
BEGIN
PAQUETE_MUTANTE.SALMAX:=:NEW.PRESUPUESTO;
    IF PAQUETE_MUTANTE.SALMAX>SALARIO_MAX THEN --SI EL PRESUPUESTO ES MAYOR QUE EL SARAIO MAXIMO
         RAISE_APPLICATION_ERROR(-200002,'PRESUPUESTO EQUIPO MAYOR QUE 200.000.');--EJECUTAR ERROR PROPIO
    END IF;  
END TRIG_SAL_MAX_EQUIPO;

SELECT * FROM USER_TRIGGERS;